import {
    Users,
    Briefcase,
    FileText,
    DollarSign,
    Wrench,
    BarChart3,
    Settings,
    Shield,
    Search,
    Plus,
    Bell,
    MapPin,
    CheckCircle2,
    AlertCircle,
    Check,
    X,
    ChevronRight,
    Star,
    Printer,
    Menu,
    LogOut,
    Eye,
    Calendar,
    Filter,
    Calculator,
    History,
    Trash2,
    Phone,
    MessageSquare,
    Play
} from "lucide-react";

export const Icons = {
    logo: Printer,
    users: Users,
    sales: Briefcase,
    leads: Users,
    quotes: FileText,
    accounting: DollarSign,
    service: Wrench,
    reports: BarChart3,
    settings: Settings,
    admin: Shield,
    search: Search,
    add: Plus,
    bell: Bell,
    location: MapPin,
    check: CheckCircle2,
    warning: AlertCircle,
    menu: Menu,
    logout: LogOut,
    arrowRight: ChevronRight,
    calendar: Calendar,
    filter: Filter,
    calculator: Calculator,
    history: History,
    delete: Trash2,
    view: Eye,
    printer: Printer,
    phone: Phone,
    message: MessageSquare,
    play: Play
};
